### ISSUE TITLE
Add Protection Deletion to DynamoDB tables

### ISSUE THREAD

**Issue by Digi-Deli** [cloudposse/terraform-aws-dynamodb#110]
## Describe the Feature

Add deletion_protection_enabled to the module. Terraform has this as an optional argument

## Expected Behavior

When the flag set to true the dynamo table to be created or modified with Deletion Protection on 

## Use Case

We would like to be able to use the flag to avoid accidentally deleting DynamoDB tables. This flag is being enabled by terraform as an optional argument (defaults to false). See documentation [deletion_protection_enabled](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#deletion_protection_enabled)

**Comment by lplazas** [comment]
I am in need of this feature internally as well, if any of the maintainers (@milldr @alexjurkiewicz @aknysh @nitrocode) can confirm this is something that you want to see implemented I can work on it.

**Comment by nitrocode** [comment]
Yes please propose the change and it can be reviewed

**Comment by nnsense** [comment]
I suppose this issue can be closed, the related PR has been merged long ago.
