### ISSUE TITLE
Range key is required?

### ISSUE THREAD

**Issue by fireboy1919** [cloudposse/terraform-aws-dynamodb#13]
Terraform's aws provider doesn't require a range key.  Why does this provider?  
What if you want to make a table that doesn't use a range key?

https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html

**Comment by JoviTelstra** [comment]
+1

**Comment by aknysh** [comment]
@fireboy1919 
@JoviTelstra 

Addressed in https://github.com/cloudposse/terraform-aws-dynamodb/pull/17
