### ISSUE TITLE
Attribute type for hash and range key is hard-coded to String

### ISSUE THREAD

**Issue by sahil21** [cloudposse/terraform-aws-dynamodb#24]
The primary keys (Hash and Range) can accept 3 data types i.e String, Number & Binary. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html

**Comment by aknysh** [comment]
thanks @sahil21 , we'll address it

**Comment by aknysh** [comment]
@sahil21 
addressed and tagged https://github.com/cloudposse/terraform-aws-dynamodb/releases/tag/0.6.0
thanks for reporting
join our Slack community https://slack.cloudposse.com where we discuss all topics on Terraform, Kubernetes and more
