### ISSUE TITLE
billing_mode support?

### ISSUE THREAD

**Issue by shmick** [cloudposse/terraform-aws-dynamodb#30]
Hi there.

Would it be possible to have ```billing_mode``` as a config option? This is currently an option in the official [aws_dynamodb_table](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#billing_mode) resource.

Thanks.

**Comment by osterman** [comment]
@shmick certainly! We'll promptly review all PRs. =)

**Comment by shmick** [comment]
Cool. PR sent. https://github.com/cloudposse/terraform-aws-dynamodb/pull/31
