### ISSUE TITLE
Support AWS Provider 3+

### ISSUE THREAD

**Issue by jurgenweber** [cloudposse/terraform-aws-dynamodb#61]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

TF v13 changes mean older version of the AWS provider is buggy.

https://github.com/terraform-providers/terraform-provider-aws/issues/14405

## Expected Behavior

version constraints to allow latest AWS Provider 3.2 and into the future.

**Comment by mattyev87** [comment]
do we have an eta on when this will be implemented? 
Im looking to bump up to version 3 of the aws provider and this module is holding me back.

**Comment by jurgenweber** [comment]
PR has been merged, I use this module with AWS v3.....
