### ISSUE TITLE
Multiple index support?

### ISSUE THREAD

**Issue by emmekappa** [cloudposse/terraform-aws-dynamodb#7]
Is it possible to provide one or more `global_secondary_index` directives?

**Comment by Jamie-BitFlight** [comment]
Yes in https://github.com/cloudposse/terraform-aws-dynamodb/pull/6

**Comment by emmekappa** [comment]
That's great, it would be awesome multiple indexes also in https://github.com/cloudposse/terraform-aws-dynamodb-autoscaler. I'm trying the same approach.

**Comment by emmekappa** [comment]
@Jamie-BitFlight implemented in https://github.com/cloudposse/terraform-aws-dynamodb-autoscaler/pull/4

**Comment by osterman** [comment]
Thanks guys! We'll try to get to all the PRs shortly. @aknysh has been slammed with another project.

**Comment by aknysh** [comment]
@Jamie-BitFlight  @emmekappa 
Thanks guys for testing and taking the time to submit the changes.
Merged to master.
