### ISSUE TITLE
Support disabling tags in order to work with dynamodb-local

### ISSUE THREAD

**Issue by mwarkentin** [cloudposse/terraform-aws-dynamodb#90]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

We're trying to reuse our terraform configuration we've built with this module for AWS with dynamodb-local. Unfortunately dynamodb-local doesn't support tags at this time, so the module is non-functional for this use case.

```
Error: error updating DynamoDB Table (default-userToBusiness) tags: error tagging resource (arn:aws:dynamodb:ddblocal:000000000000:table/default-userToBusiness): UnknownOperationException: Tagging is not currently supported in DynamoDB Local.
```

I'd like to be able to disable tagging entirely so that I can continue to use the same module for local and AWS dynamodb tables.

## Describe Ideal Solution

Set `var.enable_tags = false` (or `var.disable_tags = true`), skip setting tags.

## Alternatives Considered

Rewrite our terraform for dynamodb-local to use another module or straight up `aws_dynamodb_table` resources.

**Comment by dotCipher** [comment]
Cool that makes sense, I'll take a look
